# Generated by Django 4.2.5 on 2023-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=100)),
                ('Profesion', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
