# Generated by Django 4.2.5 on 2023-09-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_contacto_created_contacto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contacto', verbose_name='Imagen'),
        ),
    ]
